(add-to-list 'load-path "~/.emacs.d/lisp/")
(setq exec-path (append exec-path '("/usr/local/bin/")))
(require 'quack)
(setq quack-default-program "mit-scheme")
(load "~/.emacs.d/haskell-mode/haskell-site-file.el")
(add-hook 'haskell-mode-hook 'turn-on-haskell-doc-mode)
(add-hook 'haskell-mode-hook 'turn-on-haskell-indent)
