if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

setxkbmap -option ctrl:nocaps
export LSP_USE_PLISTS=true
export LANG=en_US.UTF-8
export EDITOR='emacsclient'

GUIX_PROFILE="/home/arbn/.guix-profile"
. "$GUIX_PROFILE/etc/profile"